# Use the universal image provided by Microsoft as the base image
FROM mcr.microsoft.com/vscode/devcontainers/universal:1.0

# Install Python, pip, and Docker
RUN sudo apt-get update && sudo apt-get install -y python3 python3-pip docker.io

# Install the Python packages
RUN pip3 install --no-cache-dir requests matrix_client configparser

# Set the default user
USER vscode